/**
 * Resolves and renders the build stamp compiled into the Worker (CR-030).
 *
 * Every value has two possible sources and a defined order: an environment
 * variable set by the workflow first, then the git checkout on disk. CI is
 * authoritative because it is the only place that knows which refs were
 * *requested* — a rollback deploys explicit SHAs, and asking git afterwards
 * would report the same commit by luck rather than by record. The git fallback
 * is what makes a local build produce a real stamp instead of placeholders.
 */

import { execFileSync } from 'child_process';
import { existsSync, readFileSync } from 'fs';
import { dirname, join, resolve } from 'path';

import type { BuildInfo } from '../../src/utils/build-info.js';

/** Reads the commit at HEAD of the checkout containing `directory`. */
export type HeadReader = (directory: string) => string | null;

export interface BuildStampInput {
    /** Process environment; the workflow's resolved SHAs arrive here. */
    env: Record<string, string | undefined>;
    /** Repository root of the application checkout. */
    repositoryRoot: string;
    /** Resolved content directory — any path inside the content checkout. */
    contentDir: string;
    /** `web/package.json` version. */
    version: string;
    /** Build timestamp; injected so the renderer stays deterministic in tests. */
    now: Date;
    /** How to ask git for a commit. Injected so tests need no repositories. */
    readHead: HeadReader;
}

/**
 * Asks git for the commit at HEAD, returning null rather than throwing.
 *
 * A missing directory, a directory outside any repository, and a machine with
 * no git binary are all the same answer here: this build cannot name that
 * commit. None of them is a reason to fail a build that is otherwise fine.
 */
export const readGitHead: HeadReader = directory => {
    if (!existsSync(directory)) return null;

    try {
        const sha = execFileSync('git', ['rev-parse', 'HEAD'], {
            cwd: directory,
            encoding: 'utf-8',
            stdio: ['ignore', 'pipe', 'ignore'],
        });
        return sha.trim() || null;
    } catch {
        return null;
    }
};

/**
 * Where story-crafter is checked out.
 *
 * Mirrors `storyCrafterRoot` in `scripts/sync-stories.ts` deliberately rather
 * than importing it: that module is a script with its own execution, and it
 * sits outside this program's tsconfig. If one of the two ever moves, the
 * stories in the build and the commit stamped beside them would disagree, so
 * the duplication is a fact worth keeping visible.
 */
export function resolveStoryRoot(
    env: Record<string, string | undefined>,
    repositoryRoot: string
): string {
    const override = env.STORY_CRAFTER_PATH;
    return override ? resolve(override) : resolve(repositoryRoot, '..', 'story-crafter');
}

/**
 * Environment first, then the checkout on disk, then unknown.
 */
export function resolveRevision(
    fromEnvironment: string | undefined,
    directory: string | null,
    readHead: HeadReader
): string | null {
    const trimmed = fromEnvironment?.trim();
    if (trimmed) return trimmed;
    if (!directory) return null;
    return readHead(directory);
}

export function createBuildInfo(input: BuildStampInput): BuildInfo {
    const { env, repositoryRoot, contentDir, version, now, readHead } = input;

    return {
        builtAt: now.toISOString(),
        version,
        // GITHUB_EVENT_NAME is set by Actions on every run and by nothing else,
        // so its absence is the signal that this build is not a deployment.
        trigger: env.GITHUB_EVENT_NAME?.trim() || 'local',
        revisions: {
            app: resolveRevision(env.BUILD_APP_SHA, repositoryRoot, readHead),
            content: resolveRevision(env.BUILD_CONTENT_SHA, contentDir, readHead),
            story: resolveRevision(
                env.BUILD_STORY_SHA,
                resolveStoryRoot(env, repositoryRoot),
                readHead
            ),
        },
    };
}

/** Reads the version from a package.json, or `0.0.0` if it has none. */
export function readPackageVersion(packageJsonPath: string): string {
    try {
        const parsed: unknown = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
        if (parsed && typeof parsed === 'object' && 'version' in parsed) {
            const version = (parsed as { version: unknown }).version;
            if (typeof version === 'string' && version.trim()) return version.trim();
        }
    } catch {
        // Fall through to the default below.
    }
    return '0.0.0';
}

export function renderBuildData(info: BuildInfo): string {
    return `/**
 * Auto-generated build stamp.
 * DO NOT EDIT MANUALLY - this file is generated by scripts/build-posts.ts
 *
 * Describes the build that produced the bundle this file is compiled into
 * (CR-030). Git-ignored and regenerated per build, exactly like posts-data.ts.
 */

import type { BuildInfo } from './build-info.js';

export const buildInfo: BuildInfo = ${JSON.stringify(info, null, 2)};
`;
}

/**
 * Assembles the stamp for a build rooted at `webDirectory` (web/).
 */
export function buildStampFor(
    webDirectory: string,
    contentDir: string,
    env: Record<string, string | undefined>,
    now: Date = new Date(),
    readHead: HeadReader = readGitHead
): BuildInfo {
    return createBuildInfo({
        env,
        repositoryRoot: dirname(webDirectory),
        contentDir,
        version: readPackageVersion(join(webDirectory, 'package.json')),
        now,
        readHead,
    });
}
