/**
 * Build script to generate posts data at build time.
 * This reads all markdown files from the posts directory and generates
 * a TypeScript file with the parsed post data embedded.
 * 
 * This is necessary because Cloudflare Workers don't have filesystem access.
 */

import { readFileSync, readdirSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname, extname, basename } from 'path';
import { fileURLToPath } from 'url';
import { marked } from 'marked';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

interface PostMetadata {
    title: string;
    date?: string;
    author?: string;
    description?: string;
    tags?: string[];
    [key: string]: string | string[] | undefined;
}

interface Post {
    slug: string;
    metadata: PostMetadata;
    content: string;
    html: string;
}

/**
 * Extract frontmatter from markdown content
 */
function extractFrontmatter(content: string): { frontmatter: Record<string, string | string[]>; body: string } {
    const frontmatterRegex = /^---\s*\n([\s\S]*?)\n---\s*\n([\s\S]*)$/;
    const match = content.match(frontmatterRegex);
    
    if (!match) {
        return { frontmatter: {}, body: content };
    }
    
    const frontmatterText = match[1];
    const body = match[2];
    const frontmatter: Record<string, string | string[]> = {};
    
    frontmatterText.split('\n').forEach(line => {
        const colonIndex = line.indexOf(':');
        if (colonIndex > 0) {
            const key = line.substring(0, colonIndex).trim();
            let value = line.substring(colonIndex + 1).trim();
            
            // Handle array values (comma-separated or YAML-style)
            if (value.startsWith('[') && value.endsWith(']')) {
                // JSON-style array
                try {
                    frontmatter[key] = JSON.parse(value);
                } catch {
                    frontmatter[key] = value.slice(1, -1).split(',').map(s => s.trim().replace(/^["']|["']$/g, ''));
                }
            } else {
                // Regular string value
                frontmatter[key] = value.replace(/^["']|["']$/g, '');
            }
        }
    });
    
    return { frontmatter, body };
}

/**
 * Parse a single markdown file
 */
function parseMarkdownFile(filePath: string, slug: string): Post {
    const content = readFileSync(filePath, 'utf-8');
    const { frontmatter, body } = extractFrontmatter(content);
    
    // Parse markdown to HTML
    const html = marked.parse(body) as string;
    
    // Extract metadata
    const metadata: PostMetadata = {
        title: (frontmatter.title as string) || slug,
        date: frontmatter.date as string | undefined,
        author: frontmatter.author as string | undefined,
        description: frontmatter.description as string | undefined,
        tags: frontmatter.tags as string[] | undefined,
        ...frontmatter,
    };
    
    return {
        slug,
        metadata,
        content: body,
        html,
    };
}

/**
 * Get all posts from the posts directory
 */
function getAllPosts(postsDir: string): Post[] {
    const posts: Post[] = [];
    
    if (!existsSync(postsDir)) {
        console.warn(`⚠️ Posts directory not found: ${postsDir}`);
        return posts;
    }
    
    const files = readdirSync(postsDir);
    
    for (const file of files) {
        const filePath = join(postsDir, file);
        
        if (extname(file) === '.md') {
            const slug = basename(file, '.md');
            const post = parseMarkdownFile(filePath, slug);
            posts.push(post);
            console.log(`  📄 Parsed: ${file}`);
        }
    }
    
    // Sort by date if available, otherwise by title
    return posts.sort((a, b) => {
        if (a.metadata.date && b.metadata.date) {
            return new Date(b.metadata.date).getTime() - new Date(a.metadata.date).getTime();
        }
        return a.metadata.title.localeCompare(b.metadata.title);
    });
}

/**
 * Generate the posts data file
 */
function generatePostsDataFile(posts: Post[], outputPath: string): void {
    const output = `/**
 * Auto-generated posts data file.
 * DO NOT EDIT MANUALLY - this file is generated by scripts/build-posts.ts
 * 
 * Generated at: ${new Date().toISOString()}
 */

import type { Post } from './markdown.js';

export const postsData: Post[] = ${JSON.stringify(posts, null, 2)};
`;
    
    // Ensure the output directory exists
    const outputDir = dirname(outputPath);
    if (!existsSync(outputDir)) {
        mkdirSync(outputDir, { recursive: true });
    }
    
    writeFileSync(outputPath, output, 'utf-8');
}

// Main execution
const postsDir = join(__dirname, '../posts');
const outputPath = join(__dirname, '../src/utils/posts-data.ts');

console.log('📦 Building posts data...');
console.log(`  Source: ${postsDir}`);
console.log(`  Output: ${outputPath}`);
console.log('');

const posts = getAllPosts(postsDir);

generatePostsDataFile(posts, outputPath);

console.log('');
console.log(`✅ Generated posts data with ${posts.length} post(s)`);

